# Generated by Django 4.1.2 on 2024-04-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Permissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='users',
        ),
    ]
