# Generated by Django 4.1.2 on 2024-04-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permissions', '0002_remove_userrole_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='actual_roles',
            field=models.BooleanField(default=True),
        ),
    ]
