# Generated by Django 4.1.2 on 2024-04-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permissions', '0004_alter_userrole_actual_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
