# Generated by Django 4.1.2 on 2024-04-09 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_userprofile_role'),
        ('Permissions', '0005_alter_userrole_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolepermission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile', unique=True),
        ),
    ]
