# Generated by Django 4.1.2 on 2024-04-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permissions', '0006_alter_userrolepermission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepermission',
            name='can_access',
            field=models.BooleanField(default=False),
        ),
    ]
